version: '3.7'

services:

  backend-gate:
    image: gateway-service:latest
    container_name: Oauth-client
    ports:
      - "8082:8082"
    depends_on:
      - keycloak
    networks:
      - envoy-network

  keycloak:
    image: keycloak/keycloak:latest
    container_name: keycloak-new
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - "8080:8080"
    networks:
      - envoy-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - envoy-network

  envoy:
    image: envoyproxy/envoy:v1.26.0
    ports:
      - "9990:9990"
    volumes:
      - .EnvoyConfig/OptimizedEnvoy.yaml:/etc/envoy/OptimizedEnvoy.yaml
    networks:
      - envoy-network
    depends_on:
      - keycloak

networks:
  envoy-network:
    driver: bridge
volumes:
  redis-data:
    driver: local