version: '3.7'

services:

  demo_redis:
    image: redis:latest
    container_name: demo_redis
    ports:
      - "6370:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - demo_gateway_network

  demo_backend-gateway:
    image: gateway_service:latest
    container_name: demo_Oauth_client
    ports:
      - "8082:8082"
    networks:
      - demo_gateway_network
    depends_on:
      - demo_redis
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      BACKEND_URL : ${BACKEND_URL}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      GRANT_TYPE: ${GRANT_TYPE}
      ISSUER: ${ISSUER}
      GW_CLIENT_ID: ${GW_CLIENT_ID}
      GW_CLIENT_SECRET: ${GW_CLIENT_SECRET}
      GW_GRANT_TYPE: ${GW_GRANT_TYPE}
      GW_ISSUER: ${GW_ISSUER}
  demo_envoy:
    image: envoyproxy/envoy:v1.26.0
    container_name: demo_envoy
    ports:
      - "9990:9990"
      - "9901:9901"
    volumes:
      - ./envoyConfig/OptimizedEnvoy.yaml:/etc/envoy/OptimizedEnvoy.yaml
      - ./json.lua:/usr/local/share/lua/5.1/json.lua
    command: [ "envoy", "--config-path", "/etc/envoy/OptimizedEnvoy.yaml"]

    networks:
      - demo_gateway_network

networks:
  demo_gateway_network:
    driver: bridge
volumes:
  redis-data:
    driver: local