server:
  forward-headers-strategy: framework

spring:
  security:
    oauth2:
      client:
        registration:
          user-access-client:
            client-id: access-client
            client-secret: 9HiG9RCeWM8uQuz1eBV5hYGRCwwFzAFu
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid
          gateway-client:
            client-id: gateway-client-id
            authorization-grant-type: client_credentials
            client-secret: vSPS7vk9nqcHhlfUjprskzC1d9L4lJHQ
            scope: openid, profile, email
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/rayen-realm
  data:
    redis:
      port: 6379
      host: localhost
  session:
    redis:
      repository-type: default



