server:
  forward-headers-strategy: framework
  port: 8082
bankerise:
  backend_url: ${BACKEND_URL}

spring:
  security:
    oauth2:
      client:
        registration:
          front:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            provider: keycloak
            authorization-grant-type: ${GRANT_TYPE}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
          keycloak:
            client-id: ${GW_CLIENT_ID}
            client-secret: ${GW_CLIENT_SECRET}
            scope: openid, profile, email
            authorization-grant-type: ${GW_GRANT_TYPE}
            provider: gw-auth
        provider:
          keycloak:
            issuer-uri: ${ISSUER}
          gw-auth:
            issuer-uri: ${GW_ISSUER}
  data:
    redis:
      port: ${SPRING_DATA_REDIS_PORT}
      host: ${SPRING_DATA_REDIS_HOST}
  session:
    redis:
      repository-type: default
