spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: access
            client-secret: CfqPpAWdKDnbK8rEsZGMrog1TbSFEsqE
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/rayen-realm
            authorization-uri: http://localhost:8080/realms/rayen-realm/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/rayen-realm/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/rayen-realm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/realms/rayen-realm/protocol/openid-connect/certs

  data:
    redis:
      host: localhost
      port: 6379
  session:
    timeout: 30m

