server:
  forward-headers-strategy: framework
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: access-client
            client-secret: 9HiG9RCeWM8uQuz1eBV5hYGRCwwFzAFu
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/rayen-realm
  data:
    redis:
      port: 6379
      host: localhost
  session:
    redis:
      repository-type: default



