server:
  forward-headers-strategy: framework
  port: 8082
bankerise:
  backend_url: "http://showcase-retail-api.pres.proxym-it.net/bankerise-platform"

spring:
  security:
    oauth2:
      client:
        registration:
          front:
            client-id: front
            client-secret: uAyELzwAuC5V3bgNsUBdF8mXu1xlrRYs
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
          keycloak:
            client-id: api_gateway_front
            client-secret: nEqjCaEp1IxJgDT7s9PCaud6cN3RVRCe
            scope: openid, profile, email
            authorization-grant-type: client_credentials
            provider: gw-auth
        provider:
          keycloak:
            issuer-uri: http://platform-keycloak.pres.proxym-it.net/realms/showcase-retail-dev
          gw-auth:
            issuer-uri: http://platform-keycloak.pres.proxym-it.net/realms/showcase-admin-dev


  data:
    redis:
      port: 6379
      host: localhost
  session:
    redis:
      repository-type: default



